name: Collect angular project test covarage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: npm i
      - name: Run tests and collect coverage
        run: npm test
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ./coverage/app/cobertura-coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
